version: '3.8'

services:
  healthchecks-front:
    image: ghcr.io/rikardronnkvist/healthchecks-front:latest
    container_name: healthchecks-front
    ports:
      - "3000:3000"
    environment:
      - HEALTHCHECKS_APIKEY=${HEALTHCHECKS_APIKEY}
      - HEALTHCHECKS_NAME=Health Checks
      - HEALTHCHECKS_URL=https://healthchecks.io
    restart: unless-stopped
