version: '3.8'

services:
  healthchecks-front:
    image: ghcr.io/rikardronnkvist/healthchecks-front:latest
    container_name: healthchecks-front
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_APIKEY=${NEXT_PUBLIC_APIKEY}
      - NEXT_PUBLIC_NAME=${NEXT_PUBLIC_NAME:-Health Checks}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL:-https://healthchecks.io}
    restart: unless-stopped
